version: '3'

services:
  db:
    hostname: db
    image: postgres:9.4
    restart: always
    env_file: .env
    ports:
      - "5432:5432"
    volumes:
      - ./postgres-data:/var/lib/postgresql/data

  app:
    build: .
    restart: always
    entrypoint: ./run_app.sh
    volumes:
      - ./app:/code/app
    depends_on:
      - db
    ports:
      - "80:8000"
    env_file: .env
